### ISSUE TITLE
Proposal: move state metadata to openstates/metadata

### ISSUE THREAD

**Issue by jamesturk** [openstates/metadata#1]
Another proposal.

We have a few projects that use the core metadata of the legislatures.  The list of states, what chambers they have, how many seats are in each, etc.   We'd also like to start tracking some extra metadata like which sessions work with full text search, etc.  

I think it might make sense to have this live in a central place instead of:

- ``openstates/openstates/{state}/__init__.py``
- `openstates/people/settings.py`
- bits of code duplicated in various places to convert from abbreviation to jurisdiction id, etc.

So I'm thinking we want something based on https://github.com/unitedstates/python-us that will let us do things like:

```
from openstates_metadata import states

states.get("North Carolina")
states.get("NC")
states.get("ocd-jurisdiction/country:us/state:nc") 
```

whereas right now you either have to query the database (openstates/openstates.org) or parse various files to get this information

In the short term, pupa's Jurisdiction objects would be modified to read from this data structure.  Changes to the metadata would be done in a different repository openstates/metadata.

This would not affect the declaration of scrapers on the Jurisdiction, that can & should remain in `__init__.py`

Questions:
- Does this seem OK?  Anything I'm not considering.
- With Jurisdiction.scrapers staying put, the question remains whether legislative_sessions should stay or go.  They do change more often than the rest of the metadata (seat counts, etc.) but it might be nice to have them in the other repository.  My current idea is to move it, and alter how get_session_list behavior would work.   We'd move the get_session_list functions into essentially 50ish unit tests for the metadata repo, and we'd run these tests regularly.  Breakage would mean adding a session like it does now on nightly scrape.  (As for the scrapers, a bit of planning work would decouple the idea that a session being added means that it should be scraped right away.)

cc @showerst @schneidy

**Comment by jamesturk** [comment]
I agree that assuming we move sessions keeping those session variables in here will make sense.

It seems like the key issue we'll need to solve is how things stay up to date if the data is kept in a separate place.

A few choices:
- a git submodule: scrapers, people, and openstates.org could all have a submodule.  downside is that each will need an update when a new version is released, and git submodules are a pain in the ass
- a python module: the various projects could all depend on a package released to PyPI.   installing any of them would pull the latest version of that package (versioned by date).  downside is that when running locally you'd need to rebuild docker images (or poetry update if you aren't using docker) to get it to install the latest packages.  also we'd need to automate the release of the package probably

**Comment by showerst** [comment]
Hacky (bad?) idea -- A normal separate repo, and have the scrapers pull the fresh metadata file from a hosted URL on scrape. Maybe using github pages for it if that's within the TOS?

The downside is that would make testing and local dev kind of hard, hmm

**Comment by jamesturk** [comment]
Hmm, we'd need the code to fetch/parse it in each repo (or have a less-volatile dependency) but this could work.  And yeah I'm realizing that testing the impact of changes to metadata is indeed going to be tough with the split in a lot of these scenarios.

I wonder if we  have to settle for splitting everything but sessions since those are only needed by the bill scraper, and the rest of the metadata rarely changes, so the pain of an update is more acceptable...

**Comment by showerst** [comment]
> I wonder if we have to settle for splitting everything but sessions since those are only needed by the bill scraper, and the rest of the metadata rarely changes, so the pain of an update is more acceptable...

Yeah that might make sense. A few hundred updates per two years is just a lot higher velocity than the other data.

**Comment by jamesturk** [comment]
done w/ this for now
